// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-aq1hGmXGHKsxK6lIFG1U0Rm6ijvw6D4',
    appId: '1:598474154721:web:657189a244fd794aaa0da0',
    messagingSenderId: '598474154721',
    projectId: 'test-d532e',
    authDomain: 'test-d532e.firebaseapp.com',
    storageBucket: 'test-d532e.appspot.com',
    measurementId: 'G-6KD87H0WHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKzWGyqZBggMDldI2wF6fH11ToDunsOM',
    appId: '1:598474154721:android:a0be9403701c4997aa0da0',
    messagingSenderId: '598474154721',
    projectId: 'test-d532e',
    storageBucket: 'test-d532e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuiRuHU7U3UlvXNiGvWcd7ub7EZzzbN7I',
    appId: '1:598474154721:ios:80ebfc2d7c9f5be4aa0da0',
    messagingSenderId: '598474154721',
    projectId: 'test-d532e',
    storageBucket: 'test-d532e.appspot.com',
    iosClientId: '598474154721-4l1j8c9v74vv1ue2sp6kbujc41qr9sm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuiRuHU7U3UlvXNiGvWcd7ub7EZzzbN7I',
    appId: '1:598474154721:ios:80ebfc2d7c9f5be4aa0da0',
    messagingSenderId: '598474154721',
    projectId: 'test-d532e',
    storageBucket: 'test-d532e.appspot.com',
    iosClientId: '598474154721-4l1j8c9v74vv1ue2sp6kbujc41qr9sm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningflutter',
  );
}
